maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures haproxy"
version           "0.6"

depends "apt"
depends "logrotate"
depends "rsyslog"
depends "ssl_certificates", ">= 0.4.0"
depends "bluepill"
