default.fcgiwrap[:user] = "www-data"
default.fcgiwrap[:group] = "www-data"
default.fcgiwrap[:pid_file] = "/var/run/fcgiwrap.pids"
default.fcgiwrap[:port] = "47000"
default.fcgiwrap[:version] = "fcgiwrap_1.0.3-1ppa1_amd64"
default.fcgiwrap[:socket] = "/var/run/fcgiwrap.socket"
