default[:postgresql][:version] = "9.2"
default[:postgresql][:debversion] = "9.2.3-1.pgdg60+1"
default[:postgresql][:deb_release] = "squeeze-pgdg"
default[:postgresql][:manage_keys] = false
default[:postgresql][:interfaces] = []
default[:postgresql][:networks] = []
default[:postgresql][:port] = 5432
default[:postgresql][:shared_buffers] = "128kB"
default[:postgresql][:effective_cache_size] = "128MB"
default[:postgresql][:shmmax] = 33554432
default[:postgresql][:shmall] = 2097152
default[:postgresql][:blockdev] = {}
default[:postgresql][:log_language] = "en_US.UTF-8"
default[:postgresql][:lc_language] = "en_US.UTF-8"
default[:postgresql][:text_search_config] = "pg_catalog.english"
default[:postgresql][:datestyle] = 'iso, dmy'
default[:postgresql][:max_connections] = 100
default[:postgresql][:wal_level] = "hot_standby"
default[:postgresql][:max_wal_senders] = 5
default[:postgresql][:wal_keep_segments] = 32
default[:postgresql][:hot_standby] = "on" 
default[:postgresql][:hot_standby_feedback] = "on"
default[:postgresql][:archive_command] = "/bin/true"
default[:postgresql][:archive_mode] = "on"
default[:postgresql][:archive_timeout] = 180
default[:postgresql][:superuser_reserved_connections] = 10
default[:postgresql][:ssl] = false
default[:postgresql][:temp_buffers] = "8MB"
default[:postgresql][:work_mem] = "64kB"
default[:postgresql][:maintenance_work_mem] = "1MB"
default[:postgresql][:effective_io_concurrency] = 1
default[:postgresql][:fsync] = "off"
default[:postgresql][:synchronous_commit] = "off"
default[:postgresql][:commit_delay] = 0
default[:postgresql][:commit_siblings] = 5
default[:postgresql][:checkpoint_segments] = 16
default[:postgresql][:checkpoint_timeout] = 300
default[:postgresql][:checkpoint_completion_target] = 0.5
default[:postgresql][:log_min_duration_statement] = 2000
default[:postgresql][:autovacuum_max_workers] = 3
default[:postgresql][:autovacuum_naptime] = "1min"
default[:postgresql][:random_page_cost] = 4.0
default[:postgresql][:timezone] = "GMT"
default[:postgresql][:log_lock_waits] = "on"
default[:postgresql][:max_standby_streaming_delay] = 30
default[:postgresql][:max_standby_archive_delay] = 30
default[:postgresql][:log_checkpoints] = "on"
default[:postgresql][:wal_sync_method] = "fdatasync"
default[:postgresql][:shared_preload_libraries] = []
default[:postgresql][:vacuum_cost_delay] = 0
default[:postgresql][:vacuum_cost_limit] = 200
default[:postgresql][:autovacuum_vacuum_cost_delay] = 20
default[:postgresql][:autovacuum_vacuum_cost_limit] = -1
default[:postgresql][:log_autovacuum_min_duration] = 10000

default[:postgresql][:track_activity_query_size] = 1024

## pg_stat_statements
default[:postgresql][:pg_stat_statements_max] = 1000
default[:postgresql][:pg_stat_statements_track] = "top"
default[:postgresql][:pg_stat_statements_track_utility] = "on"
default[:postgresql][:pg_stat_statements_save] = "on"

## pg_stat_plans
default[:postgresql][:pg_stat_plans_max] = 10000
default[:postgresql][:pg_stat_plans_track] = 'all'
