maintainer        "Joshua Sierles"
maintainer_email  "joshua@diluvia.net"
description       "Configures rails apps"
version           "0.12.0"
depends           "users"
depends           "unicorn"
depends           "logrotate"
depends           "ssl_certificates"
depends           "bundler"
depends           "nginx"
depends           "eye"
